### ISSUE TITLE
Write access to downloads folder doesn't work on hosts without UID 33 and UID 1000

### ISSUE THREAD

**Issue by gangefors** [diameter/rtorrent-rutorrent#13]
I'm trying to get this to run on a Synology NAS where no user named www-data with UID/GID 33/33 exists and user accounts starts at UID 1024. When starting the container rtorrent fails to start due to no proper write access to the folders.

Please make write access to the downloads folder configurable. Env vars or similar should do.
Best would be if I can specify an UID or GID with r+w access to all folders within ./downloads on the host.

I'm gonna try to fix this myself but I wanted to file a report to be able to track this issue.

**Comment by viper151** [comment]
Hello @gangefors 
Did you find a solution to this? I'm trying to run 2 different containers at the same box for 2 different users and the docker run command always uses the first user to read folders

**Comment by gangefors** [comment]
I solved it by using env vars when running the container and modifying the startup.sh script to use these to update where needed.

Check out my [fork](https://github.com/gangefors/rtorrent-rutorrent) to see how I solved it for my Synology NAS. I haven't tested it for multiple users, only for multiple containers with the same user.

I have noticed that this is a common pitfall when moutning in host volumes where the UIDs/GIDs in the container doesn't map well with the host.

**Comment by viper151** [comment]
It actually worked :) :+1: 
I simply changed the uid and gid in startup.sh and it worked perfectly fine. Only if this could be done as env variables when creating the container (didn't see how I could do that with your fork) and merged in this official release :)

**Comment by gangefors** [comment]
In my fork I use `$ docker run -e USR_ID=<id> -e GRP_ID=<id> -e ADM_GID=<id> ...`

This is then used in the startup scrip as follows:
```
# Set rtorrent user and group id
RT_UID=${USR_ID:=1000}
RT_GID=${GRP_ID:=100}
# Set special administrator group on .rtorrent folder if specified
RT_ADM=${ADM_GID:=100}
```

**Comment by diameter** [comment]
fixed

**Comment by dmemedo** [comment]
Sorry to bump this.
But in startup-nginx.sh, shouldn't we be using  RT_UID=${USR_ID:=1000}, RT_GID=${GRP_ID:=100} instead of www-data:www-data?

**Comment by gangefors** [comment]
@dmemedo At least it's been updated to 1000:1000 in the latest script.
https://github.com/diameter/rtorrent-rutorrent-shared/blob/master/startup-rtorrent.sh#L6

You are still free to customize with env vars.

**Comment by dmemedo** [comment]
@gangfors, it's the case for startup-rtorrent.sh but not startup-nginx.sh script.
https://github.com/diameter/rtorrent-rutorrent-shared/blob/master/startup-nginx.sh

**Comment by gangefors** [comment]
@dmemedo So sorry, I didn't read your comment properly.

I see that for some reason these rows are in that shell script.
```
mkdir -p /downloads/.rutorrent/torrents
chown -R www-data:www-data /downloads/.rutorrent
```

I can't for my life understand why they are there and why the .rtorrent folder need to be owned by www-data. www-data should have read access to that folder but I see no files that need to be written to that folder by the nginx service.
But I haven't looked into this repo and the changes made since i forked it years ago, so I can't say why they are there.

**Comment by dmemedo** [comment]
it's rutorrent permissions not rtorrent
I hope diameter still maintains this repo

**Comment by gangefors** [comment]
Or you could just do a PR when you get it working. :)

**Comment by o6uoq** [comment]
> I hope diameter still maintains this repo

If not, then I hope someone submits a PR with updates!

**Comment by dmemedo** [comment]
> Or you could just do a PR when you get it working. :-)

I'd love to, but I'm using Docker on a Synology NAS, I don't know if I can install images outside of docker hub

**Comment by o6uoq** [comment]
@dmemedo Docker should run as a daemon/service on the Synology NAS. Have you tried logging in via shell and pulling + running images from there?
