### ISSUE TITLE
Unpack not working

### ISSUE THREAD

**Issue by viper151** [diameter/rtorrent-rutorrent#18]
Hello,

I tried using the unpacking option from the files but it didn't work for some reason and I realized that rar wasn't installed in the docker and apt-get install rar wasn't working for some reason so I installed it like this:

cd /tmp
wget http://www.rarlab.com/rar/rarlinux-x64-5.3.b4.tar.gz
tar -zxvf rarlinux-*.tar.gz
cd rar
cp rar unrar /usr/local/bin

And then it worked. Am I missing something in this step? Will this break something?
Can it be added in the docker?

**Comment by chris400** [comment]
The docker uses unrar-free, not unrar. So the binary is called 'unrar-free',

**Comment by viper151** [comment]
Still out of the box it doesn't seem to work.
When using the unpack function on one of the rar files, I get a failure.

**Comment by diameter** [comment]
Fixed
