### ISSUE TITLE
How do I get my downloaded file out of the container?

### ISSUE THREAD

**Issue by zag1958** [diameter/rtorrent-rutorrent#29]
As the title suggests, I need to download the files from the container to my home server (docker is running a dedicated server and I only have remote access through SSH).  I prefer to lftp if possible but I am not sure how to lftp over ssh which is my usual method.  This is my first attempt at using docker so I apologize for the newbie question.

**Comment by diameter** [comment]
Hi @zag1958 
If you ran the container as suggested in the README.md, your downloaded files are not in the container but rather in the location you should have specified via '-v' switch. So how you access files in that location is not docker-related.

**Comment by elgallo** [comment]
sorry I was following directions found [here](https://tuananh.org/2015/11/07/possibly-the-easiest-way-to-setup-rtorrent-rutorrent/)

this is by far the easiest r/utorrent setup ever and loved the responsiveness. I'll read the README.md here and hopefully get this to work as desired. thanks for your response

**Comment by diameter** [comment]
@elgallo , you are welcome!
