### ISSUE TITLE
autodl-irssi plugin

### ISSUE THREAD

**Issue by jefferymcjefferson** [diameter/rtorrent-rutorrent#37]
Is there any interest of providing support for the [autodl-irssi plugin](https://github.com/autodl-community/autodl-irssi)? I've got this working, and I'd like to share.

I can either create a PR to this project, a PR to the [shared repo](https://github.com/diameter/rtorrent-rutorrent-shared), or fork off a child image off of your image.

**Comment by diameter** [comment]
@jefferymcjefferson if you create a pull request, I'll be happy to add this plugin to the image. thanks.

**Comment by jefferymcjefferson** [comment]
[Main repo PR](https://github.com/diameter/rtorrent-rutorrent/pull/38)
[Shared repo PR](https://github.com/diameter/rtorrent-rutorrent-shared/pull/3)

We can keep discussing this in the PRs, if necessary.
