### ISSUE TITLE
Cant open irssi session to check connectivity

### ISSUE THREAD

**Issue by martikainen87** [diameter/rtorrent-rutorrent#40]
Tried finding the command to open the current irssi session to be able to verify connectivity and function of the autodl. Neither screen or dtach seems to work. Whats the correct way of accessing the session? 

(tried to find a way to contact you without raising an issue, but couldnt find any email etc).

Thanks for an awesome container!

**Comment by jefferymcjefferson** [comment]
```
docker exec -ti <CONTAINERNAME> bash
cat /var/log/supervisor/irssi-stdout*
```

Not the prettiest, but it works.

You might want to `reset` your terminal, when done with that. Sometimes, `cat`ting it out makes your session wonky.
