### ISSUE TITLE
exposing rutorrent config

### ISSUE THREAD

**Issue by fswings** [diameter/rtorrent-rutorrent#5]
I was expecting a config folder in my downloads directory but none exists as per your README.md

I'm running the 64 bit edition.

**Comment by gangefors** [comment]
Works when I test it.
$ docker run -dt --name rt -P -v ~/dls:/downloads diameter/rtorrent-rutorrent
$ ls -la ~/dls/
drwxr-xr-x  3 www-data www-data 4,0K feb 17 12:47 config/
drwxr-xr-x  2     1000     1000 4,0K feb 17 12:47 .session/
drwxr-xr-x  2     1000     1000 4,0K feb 17 12:47 watch/

**Comment by diameter** [comment]
fixed
