### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by BadAssWright** [diameter/rtorrent-rutorrent#58]
Having issues with the latest build since PHP 7.0 is EOL and PHP 7.2 is now installed by default. I have to modify /etc/nginx/sites-enabled/rutorrent-tls.nginx to use the PHP 7.2 socket and then restart nginx.

**Comment by diameter** [comment]
@BadAssWright I fixed the config and rebuilt the containers. please try again.

**Comment by BadAssWright** [comment]
@diameter That has resolved the issue, thank you fixing it so fast.
