### ISSUE TITLE
Bad response from server for unknown reason

### ISSUE THREAD

**Issue by PetiZila** [diameter/rtorrent-rutorrent#72]
Hello, since now a week and a lot of tests, I decided to come to you with my error.

> Bad response from server: (0 [error,getplugins])

or

> Bad response from server: (500 [error,getplugins])

It started happening suddenly with no changes on the server nor the container itself.
here is the run command:

> sudo docker run -dt --name rto-peti -p 8081:80 -p 49161:49160/udp -p 49162:49162 -v ~/seedbox/downloads:/downloads diameter/rtorrent-rutorrent:stable

I've tried switching to stable-32, latest and latest-32 as well, that didnt change anything.

here is the "docker logs" of the container

> /usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2019-10-08 19:42:40,418 CRIT Supervisor running as root (no user in config file)
2019-10-08 19:42:40,447 CRIT Server 'unix_http_server' running without any HTTP authentication checking
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2019-10-08 19:44:56,499 CRIT Supervisor running as root (no user in config file)
2019-10-08 19:44:56,507 CRIT Server 'unix_http_server' running without any HTTP authentication checking
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2019-10-10 12:04:29,835 CRIT Supervisor running as root (no user in config file)
2019-10-10 12:04:29,913 CRIT Server 'unix_http_server' running without any HTTP authentication checking
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2019-10-10 12:15:21,859 CRIT Supervisor running as root (no user in config file)
2019-10-10 12:15:21,866 CRIT Server 'unix_http_server' running without any HTTP authentication checking

**Comment by euskadi31** [comment]
I have the same problem

**Comment by euskadi31** [comment]
@diameter you have an idea ?

**Comment by PetiZila** [comment]
I fixed it. 

It does that when your docker cant get more disk space.
Clean up containers you dont use anymore and clear docker cache. Or Expand the disk space if you can.

Hope that helps
