### ISSUE TITLE
SSL Bug Affecting Downloads

### ISSUE THREAD

**Issue by jefferymcjefferson** [diameter/rtorrent-rutorrent#74]
It appears that an SSL bug with autodl-irssi is currently affecting HTTPS file downloads. A manual fix is provided [here](https://old.reddit.com/r/seedboxes/comments/c9cdir/autodlirss_command_error/eszubn9/).

It looks like the `latest` and `stable` tags haven't been updated in four months. That's likely all that is required.

**Comment by diameter** [comment]
@jefferymcjefferson ,  I forced rebuild of all the images, could you please check if the bug has gone?
